### ISSUE TITLE
Cannot create process Win32Error:1314

### ISSUE THREAD

**Issue by coder4temp** [BeichenDream/GodPotato#1]
i get this when i run godpotato.exe -cmd "cmd /c whoami"

[*] CombaseModule: 0x140708724932608                                                                                                                                                                       
[*] DispatchTable: 0x140708727387576                                                                                                                                                                       
[*] UseProtseqFunction: 0x140708726719552                                                                                                                                                                  
[*] UseProtseqFunctionParamCount: 6                                                                                                                                                                        
[*] HookRPC                                                                                                                                                                                                
[*] Start PipeServer                                                                                                                                                                                       
[*] Trigger RPCSS                                                                                                                                                                                          
[*] CreateNamedPipe \\.\pipe\61df8bc5-e178-4bde-b4be-2b06da419ef1\pipe\epmapper                                                                                                                            
[*] DCOM obj GUID: 00000000-0000-0000-c000-000000000046                                                                                                                                                    
[*] DCOM obj IPID: 00001002-0a68-ffff-a0b1-b34175dda8b1                                                                                                                                                    
[*] DCOM obj OXID: 0xd567cc57206845d7                                                                                                                                                                      
[*] DCOM obj OID: 0x464e3d26a045fbe3                                                                                                                                                                       
[*] DCOM obj Flags: 0x281                                                                                                                                                                                  
[*] DCOM obj PublicRefs: 0x0                                                                                                                                                                               
[*] Marshal Object bytes len: 100                                                                                                                                                                          
[*] UnMarshal Object                                                                                                                                                                                       
[*] Pipe Connected!                                                                                                                                                                                        
[*] CurrentUser: NT AUTHORITY\NETWORK SERVICE                                                                                                                                                              
[*] CurrentsImpersonationLevel: Identification                                                                                                                                                             
[*] Start Search System Token
[*] Find System Token : False
[*] UnmarshalObject: 0x80070776
[*] CurrentUser: NT AUTHORITY\NETWORK SERVICE
[!] Cannot create process Win32Error:1314

**Comment by kiykomi** [comment]
I have the same error on Windows 10, Windows 11 and Windows Server 2012.

**Comment by kaliworld** [comment]
yes, me too ,in Windows 10

**Comment by kaliworld** [comment]
> 

are you sure you account have ImpersonatePrivilege ? if you run in normal user, you will get this bug.  you can type whoami /priv to check it

**Comment by kiykomi** [comment]
Got it, thanks! That's how it is.
