### ISSUE TITLE
Permission to add GodPotato to Hacktricks

### ISSUE THREAD

**Issue by sealldeveloper** [BeichenDream/GodPotato#12]
Hello!

I wanted to ask if it was alright if I referenced this tool in a HackTricks pull request, as it says we need to 'ensure that you only upload content that you own or that have permission to share it from the original author (adding a reference to the author in the added text or at the end of the page you are modifying or both)'.

Would that be alright?

Thank you,
- sealldev

**Comment by BeichenDream** [comment]
Yes, you can, you just need to credit the author and source

**Comment by sealldeveloper** [comment]
Perfecto, thank you!
