### ISSUE TITLE
Works on EN versions only

### ISSUE THREAD

**Issue by 61106960** [BeichenDream/GodPotato#2]
Thanks for your very nice tool, which works very well on an EN language Windows.
Anyhow it could be helpful if it would support other languages as well.

I have looked up the code and in 'GodPotatoContext.cs' you are searching for tokens in the context of "NT AUTHORITY\\SYSTEM".

`if (processToken.UserName == "NT AUTHORITY\\SYSTEM" && processToken.ImpersonationLevel >= TokenImpersonationLevel.Impersonation && processToken.IntegrityLevel >= SharpToken.IntegrityLevel.SystemIntegrity)`

For me, I have changed it simply to...

`if (processToken.UserName.Contains("\\SYSTEM") && processToken.ImpersonationLevel >= TokenImpersonationLevel.Impersonation && processToken.IntegrityLevel >= SharpToken.IntegrityLevel.SystemIntegrity)`

...to catch other languages too, like the German "NT-AUTORITÄT\\SYSTEM".
Very likely that you have a much better Regex in mind to cover all the different flavors of languages :-)

**Comment by BeichenDream** [comment]
Bug fixed, now matches SYSTEM users by SID

[commit](https://github.com/BeichenDream/GodPotato/commit/d5efb3fa113d8a1a6212ffc4a8fdb438eea03419)
