### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by ttsite** [BeichenDream/GodPotato#8]
为什么生成的exe文件无法用Eazfuscator.NET 之类的进行混淆操作.试了几款工具。只要混淆就出错不能正常工作

**Comment by BeichenDream** [comment]
出什么错呢

**Comment by ttsite** [comment]
> 出什么错呢

![dr](https://github.com/BeichenDream/GodPotato/assets/43260559/1f677a93-4621-4d81-b009-118a06dc7323)

**Comment by ttsite** [comment]
多谢您的修复,已看到测试正常了.
