### ISSUE TITLE
执行GodPotato-NET4.exe -cmd "cmd /c whoami"报错

### ISSUE THREAD

**Issue by lsclsclsc** [BeichenDream/GodPotato#9]
[*] CombaseModule: 0x140716114706432
[*] DispatchTable: 0x140716117048944
[*] UseProtseqFunction: 0x140716116415536
[*] UseProtseqFunctionParamCount: 6
[*] HookRPC
[*] Start PipeServer
[*] CreateNamedPipe \\.\pipe\05ca8234-4d82-429c-9e6a-a2811b406477\pipe\epmapper
[*] Trigger RPCSS
[*] DCOM obj GUID: 00000000-0000-0000-c000-000000000046
[*] DCOM obj IPID: 0000ec02-1c90-ffff-dd63-9bb045694421
[*] DCOM obj OXID: 0x6701decccb49e4c1
[*] DCOM obj OID: 0xfd67152b0da60f20
[*] DCOM obj Flags: 0x281
[*] DCOM obj PublicRefs: 0x0
[*] Marshal Object bytes len: 100
[*] UnMarshal Object
[*] Pipe Connected!
[*] CurrentUser: NT AUTHORITY\NETWORK SERVICE
[*] CurrentsImpersonationLevel: Identification
[*] Start Search System Token
[*] Find System Token : False
[*] UnmarshalObject: 0x80070776
[*] CurrentUser: NT AUTHORITY\NETWORK SERVICE
[!] Cannot create process Win32Error:1314

**Comment by wineggdrop** [comment]
error code 1314 meaning the running process does not has ImpersonatePrivilege
